In [4]:
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline


In [5]:
np.random.randint(2)

0

In [6]:
np.random.randint(2, size=10000)


array([0, 1, 1, ..., 0, 1, 1])

In [7]:
np.random.randint(2, size=10000).mean()

0.4987

In [8]:
np.random.choice([0, 1])


1

In [9]:
np.random.choice([0, 1], size=10000)


array([0, 1, 0, ..., 1, 0, 1])

In [10]:
np.random.choice([0, 1], size=10000).mean()


0.4955

In [11]:
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])


array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
np.random.choice([0,1], size=10000,p=[0.8,0.2]).mean()

array([0, 0, 0, ..., 0, 0, 1])